# Configuration for Label Actions - https://github.com/dessant/label-actions

# Actions taken when the `incomplete` label is added to issues 
incomplete:
  # Post a comment
  comment: >
    Thank you for your submission, but there isn't enough detail in the issue for us to review & move forward. The new issue template includes sections for you to fill out. Please resubmit your issue and complete the provided sections in the new item template so we can move forward on it.
  close: true
