# Configuration for Label Actions - https://github.com/dessant/label-actions

# Actions taken when the `incomplete` label is added to issues 
incomplete:
  # Post a comment
  comment: >
    Thank you for your submission, but there isn't enough detail in the issue for us to review & move forward. Please resubmit your issue. In case you need any help, reach out to us. 
  close: true
